### ISSUE TITLE
多个候选答案找出最符合题目要求的答案

### ISSUE THREAD

**Issue by tcxia** [IAAR-Shanghai/xFinder#3]
您好，想问下，能通过该项目实现给定一个题目，以及多次采样的答案，找到最符合题目要求的答案吗

**Comment by Duguce** [comment]
您好，xFinder 可以用于从大模型的输出内容中提取关键答案，例如从“The answer is A ...”中提取“A”。因此， xFinder 可以用于获取采样答案中的关键答案，但目前还不支持从多个答案中挑选出最符合题目的答案。
