### ISSUE TITLE
About KAF dataset 

### ISSUE THREAD

**Issue by liushz** [IAAR-Shanghai/xFinder#4]
Thanks for your great job!
Will you release the KAF dataset? At least the test set to reimplement the results.

**Comment by Duguce** [comment]
Thank you for your recognition and attention to our work. We plan to release the KAF dataset, in about two to four weeks. Please stay tuned.

**Comment by Duguce** [comment]
@liushz Hello, thank you for your interest in our work. Our [KAF dataset](https://huggingface.co/datasets/IAAR-Shanghai/KAF-Dataset) has been open-sourced on Hugging Face, and we have also released xFinder as a [PyPI package](https://pypi.org/project/xfinder/).
