### ISSUE TITLE
Support for Multiple Short Text Answers in Multiple-Choice Questions

### ISSUE THREAD

**Issue by cpa2001** [IAAR-Shanghai/xFinder#5]
Thank you for your exceptional work on xFinder!

I’d like to inquire whether the current version of xFinder supports multiple-choice questions where the `correct_answer` field can include multiple valid short text answers. Specifically, it seems like the `Extractor` currently returns only a single result. Is there a way to handle cases where a question has more than one correct option?

**Comment by Duguce** [comment]
Hello, thank you for your interest in our work.

Currently, xFinder does not specifically support multiple-choice questions. In cases where a question has multiple correct answers, I suggest trying to prompt the model to list all correct answers after a specific phrase, such as "The correct answers are:" and separate each answer with a fixed symbol. This should allow xFinder's `Extractor` module to extract and then match the answers to evaluate the results. Of course, this approach might be somewhat rudimentary, and we would be more than happy to discuss further to find a better solution.
