### ISSUE TITLE
Whether Answer Extraction Supports Not Providing Range and Type

### ISSUE THREAD

**Issue by Qianhao-Ren** [IAAR-Shanghai/xFinder#6]
Thanks for the great works. I noticed that the examples all require specifying the standard answer range and answer type. However, I'm not certain about the answer range for extraction. Does this task support extracting answers without providing the answer range and answer type?

**Comment by Duguce** [comment]
Thank you for your question. As you’ve noticed, the current version of xFinder primarily supports four types of questions (alphabet option / short text / categorical label / math). Specifying the standard answer range and answer type helps improve the accuracy and effectiveness of answer extraction. If these details are not provided, extraction is still possible in theory, but the performance may be slightly reduced (however, for most tasks, especially non-long-text tasks, the extraction performance is still good). If your task mainly involves extracting shorter texts, you can set the answer type to “short text” and leave the answer range empty.

Feel free to reach out if you have any further questions!

**Comment by Qianhao-Ren** [comment]
I am grateful for your detailed feedback; it has been very beneficial.
