### ISSUE TITLE
xfinder/modules/answer_extractor.py issue while getting reponse after decoding

### ISSUE THREAD

**Issue by framolfese** [IAAR-Shanghai/xFinder#7]
In the answer_extractor.py file, after invoking the tokenizer.decode method on the output_ids in the "_execute_local_inference" function, even though "skip_special_tokens" is set to True, the function "response.replace(prompt, '').strip()" does not work because the original prompt is not fully contained in the decoded output anymore. This always leads to an invalid response because the Comparator fails to match it with the correct answer.

**Comment by framolfese** [comment]
For reference, the decoding should ideally be performed as:

response = self.tokenizer.decode(
        output_ids[0][input_ids.shape[1]:], 
        skip_special_tokens=True
)

Such that the output only contains the string generated by the model, and then you can return the following:

return response.strip()

**Comment by Duguce** [comment]
Thank you for your feedback and high-quality Pull Request! The new code logic is more robust, and we have tested the updated code before successfully merging it into the main branch. We sincerely appreciate your support and contributions to the project! If you have any further questions or suggestions, please feel free to reach out to us anytime!
